#!/usr/bin/env perl

use v5.10;
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib";
use Getopt::Long::Descriptive;
use Stree;

our $VERSION = '0.1.1';

my ($opt, $usage) = describe_options(
  "$0 (v$VERSION) %o [directory]",
  [ 'help|?',           "Prints the help information and exits." ],
  [ 'version|!',        "Prints the version information and exits." ],
  [ 'all|a',            "Print all files, even hidden ones." ],
  [ 'from-file|A=s',    "Read directories from file." ],
  [ 'dirs-first|b',     "List directories before files." ],
  [ 'files-first|B',    "List files before directories." ],
  [ 'status|c',         "Sort by status change." ],
  [ 'csv|C',            "Output as CSV." ],
  [ 'dirs|d',           "List directories only." ],
  [ 'date|D',           "Print modification date." ],
  [ 'device|e',         "Print device number." ],
  [ 'prune|E',          "Do not print empty directories." ],
  [ 'full|f',           "Print full path prefix." ],
  [ 'suffix|F',         "Print custom type indicators" ],
  [ 'group|g',          "Print group name." ],
  [ 'gitignore|G',      "Use gitignore files." ],
  [ 'partial|h=i',      "Use first N bytes for hashing", { default => 256 } ],
  [ 'html|H',           "Output as HTML." ],
  [ 'no-indent|i',      "Do not indent lines." ],
  [ 'ignore|I=s',       "Ignore pattern." ],
  [ 'hash|j',           "Print SHA256 hash." ],
  [ 'json|J',           "Output as JSON." ],
  [ 'links|l',          "Follow symlinks." ],
  [ 'max-depth|L=i',    "Maximum depth", { default => 256 } ],
  [ 'markdown|M',       "Output as markdown." ],
  [ 'inodes|n',         "Print inode numbers." ],
  [ 'output|o=s',       "Send output to file." ],
  [ 'permissions|p',    "Print permissions." ],
  [ 'pattern|P=s',      "List only files matching pattern." ],
  [ 'question-marks|q', "Show non-printable as ?" ],
  [ 'quotes|Q',         "Quote file names." ],
  [ 'reverse|r',        "Reverse sort order." ],
  [ 'ignore-case|R',    "Case-insensitive matching." ],
  [ 'size|s',           "Print file size." ],
  [ 'time|t',           "Sort by modification time." ],
  [ 'user|u',           "Print user name." ],
  [ 'no-sort|U',        "Do not sort." ],
  [ 'sort-version|V',   "Version number sort." ],
  [ 'xdev|x',           "Stay on current filesystem." ],
  [ 'xml|X',            "Output as XML." ],
  [ 'yaml|Y',           "Output as YAML." ],
);

if ($opt->help)    { say $usage->text; exit }
if ($opt->version) { say "$0 v$VERSION"; exit }

my $dir = shift || '.';

my $stree = Stree->new($opt);
$stree->run($dir);
